In [1]:
import numpy as np

### Array Creation

In [2]:
'''

np.array()	        => Create array from list/tuple
np.zeros()	        => Array of zeros
np.ones()	        => Array of ones
np.empty()	        => Uninitialized array
np.arange()	        => Array with range of numbers
np.linspace()	    => Evenly spaced numbers over interval
np.eye()	        => Identity matrix
np.full()	        => Array filled with constant
np.random.rand()	=> Random floats in [0,1)
np.random.randn()	=> Random samples from normal
np.random.randint()	=> Random integers
np.random.choice()	=> Random selection from array

'''

'\n\nnp.array()\t        => Create array from list/tuple\nnp.zeros()\t        => Array of zeros\nnp.ones()\t        => Array of ones\nnp.empty()\t        => Uninitialized array\nnp.arange()\t        => Array with range of numbers\nnp.linspace()\t    => Evenly spaced numbers over interval\nnp.eye()\t        => Identity matrix\nnp.full()\t        => Array filled with constant\nnp.random.rand()\t=> Random floats in [0,1)\nnp.random.randn()\t=> Random samples from normal\nnp.random.randint()\t=> Random integers\nnp.random.choice()\t=> Random selection from array\n\n'

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
np.zeros(2)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones(4)
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [6]:

np.empty(2)
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr =np.arange(4)
arr2d = arr.reshape((2,2))
arr2d


array([[0, 1],
       [2, 3]])

In [8]:
# start → starting value of the sequence

# stop → end value of the sequence

# num → number of evenly spaced samples (default 50)

# endpoint → if True, stop is included

# retstep → if True, also return step size

# dtype → data type of output array

# np.linspace(0,10,num=5,endpoint=True,retstep=False,dtype=None)
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.random.rand(4)

array([0.87913315, 0.28767276, 0.95547159, 0.37885401])

In [11]:
np.random.randn(2)

array([-1.65992005, -1.5685965 ])

In [12]:
np.random.randint(5)

4

In [13]:
np.random.choice([1,2,3,4,5])

np.int64(5)

### Array Inspection

In [14]:
'''
arr.shape	    => Dimensions of array
arr.ndim	    => Number of dimensions
arr.size	    => Total elements
arr.dtype	    => Data type
arr.itemsize	=> Bytes per element
arr.T	        => Transpose
arr.flatten()	=> Flatten array
arr.reshape()	=> Change shape
arr.astype()	=> Change data type

'''

'\narr.shape\t    => Dimensions of array\narr.ndim\t    => Number of dimensions\narr.size\t    => Total elements\narr.dtype\t    => Data type\narr.itemsize\t=> Bytes per element\narr.T\t        => Transpose\narr.flatten()\t=> Flatten array\narr.reshape()\t=> Change shape\narr.astype()\t=> Change data type\n\n'

In [15]:
arr=np.array([[1,2,3],
             [4,5,6]])

In [16]:
arr.shape

(2, 3)

In [17]:
arr.ndim

2

In [18]:
arr.size

6

In [19]:
arr.dtype

dtype('int64')

In [20]:
arr.itemsize

8

In [21]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [23]:
arr.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [24]:
arr.astype(str)

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U21')

### Array Indexing & Slicing

In [25]:
'''
arr[i]	      => Element selection
arr[i:j]	  => Slice elements
arr[i:j:k]	  => Slice with step
arr[..., i]	  => Multi-dimensional indexing
arr.take()	  => Select elements by index
np.where()	  => Conditional selection
np.nonzero()  => Indices of non-zero elements


'''

'\narr[i]\t      => Element selection\narr[i:j]\t  => Slice elements\narr[i:j:k]\t  => Slice with step\narr[..., i]\t  => Multi-dimensional indexing\narr.take()\t  => Select elements by index\nnp.where()\t  => Conditional selection\nnp.nonzero()  => Indices of non-zero elements\n\n\n'

In [26]:
import numpy as np

arr2 = np.array([1,2,3,4,5])
print(arr2)

[1 2 3 4 5]


In [27]:
arr2[0]

np.int64(1)

In [28]:
arr2[1:2]

array([2])

In [29]:
arr2[1:4:2]

array([2, 4])

In [30]:
arr2.take([0,2])


array([1, 3])

In [31]:
np.where(arr2>2)


(array([2, 3, 4]),)

In [32]:
np.nonzero(arr2)

(array([0, 1, 2, 3, 4]),)

### Mathematical Functions

In [34]:
'''
np.add()	                    => Addition
np.subtract()	                => Subtraction
np.multiply()	                => Element-wise multiply
np.divide()	                    => Element-wise divide
np.power()	                    => Power
np.mod()	                    => Modulo
np.sqrt()	                    => Square root
np.exp()	                    => Exponential
np.log()	                    => Natural log
np.log10()	                    => Log base 10
np.sin(), np.cos(), np.tan()	            => Trig functions
np.arcsin(), np.arccos(), np.arctan()	    => Inverse trig
np.round(), np.floor(), np.ceil()	        => Rounding
'''

'\nnp.add()\t                    => Addition\nnp.subtract()\t                => Subtraction\nnp.multiply()\t                => Element-wise multiply\nnp.divide()\t                    => Element-wise divide\nnp.power()\t                    => Power\nnp.mod()\t                    => Modulo\nnp.sqrt()\t                    => Square root\nnp.exp()\t                    => Exponential\nnp.log()\t                    => Natural log\nnp.log10()\t                    => Log base 10\nnp.sin(), np.cos(), np.tan()\t            => Trig functions\nnp.arcsin(), np.arccos(), np.arctan()\t    => Inverse trig\nnp.round(), np.floor(), np.ceil()\t        => Rounding\n'

In [36]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [37]:
np.add(a,b)

array([5, 7, 9])

In [39]:
np.subtract(a,b)

array([-3, -3, -3])

In [42]:
np.multiply(a,2)

array([2, 4, 6])

In [44]:
np.divide(a,2)

array([0.5, 1. , 1.5])

In [46]:
np.power(a,2)

array([1, 4, 9])

In [47]:
np.mod(a,2)

array([1, 0, 1])

In [48]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [49]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [50]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [51]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125])

In [52]:
np.sin(100)

np.float64(-0.5063656411097588)

In [53]:
np.cos(30)

np.float64(0.15425144988758405)

In [54]:
np.tan(45)

np.float64(1.6197751905438615)

In [57]:
np.arcsin(a)

C:\Users\hp\AppData\Local\Temp\ipykernel_13692\3288507621.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(a)


array([1.57079633,        nan,        nan])

In [58]:
np.arccos(b)

C:\Users\hp\AppData\Local\Temp\ipykernel_13692\3471973207.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(b)


array([nan, nan, nan])

In [59]:
np.arctan(a)

array([0.78539816, 1.10714872, 1.24904577])

In [62]:
r=np.array([1.5,1.2,9.8])

In [63]:
np.round(r)

array([ 2.,  1., 10.])

In [64]:
np.floor(r)

array([1., 1., 9.])

In [65]:
np.ceil(r)

array([ 2.,  2., 10.])

### Statistical Function

In [ ]:
'''
np.mean()	  => Mean of array
np.median()	  => Median
np.std()	  => Standard deviation
np.var()	  => Variance
np.min()	  => Minimum
np.max()	  => Maximum
np.argmin()	  => Index of min
np.argmax()	  => Index of max
np.sum()	  => Sum of elements
np.prod()	  => Product of elements
np.cumsum()	  => Cumulative sum
np.cumprod()  => Cumulative product


'''

In [66]:
np.mean(a)

np.float64(2.0)

In [67]:
np.median(a)

np.float64(2.0)

In [68]:
np.std(a)

np.float64(0.816496580927726)

In [70]:
np.var(a)

np.float64(0.6666666666666666)

In [72]:
np.min(a)

np.int64(1)

In [73]:
np.max(a)

np.int64(3)

In [74]:
np.argmin(a)

np.int64(0)

In [75]:
np.argmax(a)

np.int64(2)

In [76]:
np.sum(a)

np.int64(6)

In [78]:
np.prod(a)

np.int64(6)

In [79]:
np.cumsum(a)

array([1, 3, 6])

In [80]:
np.cumprod(a)

array([1, 2, 6])

### Linear Algebra


In [ ]:
'''
np.dot()	    => Dot product
np.matmul()	    => Matrix multiplication
np.vdot()	    => Vector dot
np.cross()	    => Cross product
np.linalg.inv()	=> Inverse matrix
np.linalg.det()	=> Determinant
np.linalg.eig()	=> Eigenvalues & vectors
np.linalg.norm()	=> Norm of vector/matrix
np.linalg.solve()	=> Solve linear system

'''

In [82]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [83]:
np.dot(a,b)

np.int64(32)

In [84]:
np.cross(a,b)

array([-3,  6, -3])

In [85]:
np.matmul(a,b)

np.int64(32)

In [86]:
np.vdot(a,b)

np.int64(32)

In [90]:
A = np.array([
    [1,2],
    [3,4]
])

In [91]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [92]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [93]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [94]:
np.linalg.norm(A)

np.float64(5.477225575051661)

In [98]:
eq=np.array([5,10])
np.linalg.solve(A,eq)

array([0. , 2.5])

### Array Manipulation

In [ ]:
'''

np.concatenate()	  => Combine arrays
np.vstack()	          => Vertical stack
np.hstack()	          => Horizontal stack
np.split()	          => Split array
np.hsplit()	          => Horizontal split
np.vsplit()	          => Vertical split
np.tile()	          => Repeat array
np.repeat()	          => Repeat elements

'''

In [110]:
a=np.array([
    [1,2,3],
    [4,5,6]
])
b=np.array([
    [7,8,9],
    [10,11,12]
])
c=np.array([1,2,3])

In [104]:
np.concatenate((a,b),axis=0)
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [111]:
np.vstack(c)

array([[1],
       [2],
       [3]])

In [112]:
np.hstack(c)

array([1, 2, 3])

In [118]:
np.split(a,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [121]:
np.hsplit(a,1)

[array([[1, 2, 3],
        [4, 5, 6]])]

In [123]:
np.vsplit(a,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [125]:
np.tile(a,2)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [126]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [129]:
np.repeat(A,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [131]:
np.tile(c,2)

array([1, 2, 3, 1, 2, 3])

### Logical & Comparision

In [ ]:
'''
np.equal()	            => Element-wise equality
np.not_equal()	        => Element-wise not equal
np.greater()	        => Element-wise >
np.greater_equal()	    =>  >=
np.less()	            =>  <
np.less_equal()	        =>  <=
np.logical_and()	    =>  Logical AND
np.logical_or()	        =>  Logical OR
np.logical_not()	    =>  Logical NOT
np.all()	            =>  All True
np.any()	            =>  Any True

'''

In [133]:
a=np.array([1,2,3,4])
b=np.array([6,2,7,8])

In [134]:
np.equal(a,b)

array([False,  True, False, False])

In [135]:
np.not_equal(a,b)

array([ True, False,  True,  True])

In [136]:
np.greater(a,b)

array([False, False, False, False])

In [137]:
np.greater_equal(a,b)

array([False,  True, False, False])

In [138]:
np.less(a,b)

array([ True, False,  True,  True])

In [139]:
np.less_equal(a,b)

array([ True,  True,  True,  True])

In [140]:
np.logical_and(a,b)

array([ True,  True,  True,  True])

In [141]:
np.logical_or(a,b)

array([ True,  True,  True,  True])

In [142]:
np.logical_not(a,b)

array([0, 0, 0, 0])

In [146]:
np.all(a)

np.True_

In [147]:
np.any(a)

np.True_

### Sorting & Searching

In [154]:
-np.sort(-a)

array([4, 3, 2, 1])

In [159]:
np.sort(a)[::-1]

array([4, 3, 2, 1])

In [158]:
np.argsort(-a)

array([3, 2, 1, 0])

In [161]:
np.searchsorted(a,1)

np.int64(0)

In [162]:
np.unique(a)

array([1, 2, 3, 4])

In [164]:
test=[2,4,6]
np.isin(a,test)

array([False,  True, False,  True])

In [ ]:
np.where(a>=3) # Returns index

(array([2, 3]),)

In [ ]:
np.random.shuffle(a) # Mpdifies the exiting array
a

array([3, 2, 1, 4])

In [172]:
np.random.permutation(a)

array([1, 4, 2, 3])

In [ ]:
# Purpose: Return a shuffled copy of the array without modifying the original.